### ISSUE TITLE
Build artist pages

### ISSUE THREAD

**Issue by blerchin** [blerchin/dma-20-mfa-show#9]
Assemble modules in a react page for each artist
Currently blocked by #3 #4 #6 #7

**Comment by lmccart** [comment]
I can take this one

**Comment by lmccart** [comment]
Hello, working on this now. Two questions about hosting media files.

What do you want to set as the max image file size? I set the form limit to 1MB each but a lot of people sent them as gdrive links because they were too big. These images are much bigger than needed. It would be helpful to send a general email letting people know a suggested file max size and dimensions, and pointing them toward the photoshop save for web tool.

Are we hosting video files? Or should they host on vimeo or youtube and we embed?

@blerchin @hsab @brysonian

**Comment by lmccart** [comment]
I'm working on this in the artist-pages branch. If you would like to preview the pages with media, you can download the assets zip [here](http://files.lauren-mccarthy.com/transfer/assets.zip) and drop it in the `work/` directory.

**Comment by blerchin** [comment]
Hmm, I think best practice these days is to use `srcset` to provide a couple versions of each image. 1280w very compressed on mobile viewport, 2400w+ high quality on desktop with a wide viewport, maybe something in between. I realize it would be a nightmare to have all artists do this and try to share images in a consistent format. In theory it's possible to have webpack do the work, but when I've tried to do this in the past it was slow and frustrating to use.

Maybe instead of asking artists to resize we can make an imagemagick script that converts all images in the `work` folder to 3 versions with consistent naming? And have a matching component that requires these image versions and puts them in a sourceset? Or is this also too much work? Might be worth it b/c it allows for a quick view on mobile without wasting time or data, but a detailed view for actually looking at the work.

If just one image, I think 1MB is about right. Not advisable for SEO/UX purposes but in this case high quality images of the work are probably more important.


For video, it is definitely easiest to just embed youtube or vimeo since they handle all the conversions and storage. But not so great for archiving. Hosting our own videos is a pain b/c we will have to set up git LFS or other storage solution, make sure they are encoded properly for streaming etc.... Maybe we use YouTube for now and add an archival version later? I would be happy to take on that task later in June.

**Comment by hsab** [comment]
Hey just chiming in on this. but after looking around a bit I found this nice pkg called [responsive-loader](https://github.com/dscafati/responsive-loader)[fyi this link is a fork of the original] for webpack. It uses sharp which is significantly faster than node-imagemagick or jimp. Works in css and react components and overall seems to be pretty easy to integrate.

**Comment by brysonian** [comment]
I think for now maybe use the Image component and then we can modify the markup that it generates and integrate responsive loader.

**Comment by blerchin** [comment]
Sounds good. I made an issue for adding responsive images.
I am nervous about responsive-loader because the original version doesn't seem to be actively maintained (is it even compatible with webpack 4?) But if it works, that would definitely be ideal.

**Comment by hsab** [comment]
fixed this in the [artist-pages](https://github.com/blerchin/dma-20-mfa-show/tree/artist-pages) https://github.com/blerchin/dma-20-mfa-show/commit/5e310f075f9c561c5e01a25a6ae176d270d88f9f
make sure to rerun `npm install`

**Comment by blerchin** [comment]
@hsab let's leave this open until the PR is merged. Build is still failing on netlify.
